variables:
  GIT_CLEAN_FLAGS: none # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4154
  GIT_CLONE_PATH: $CI_BUILDS_DIR/isbd-server # https://stackoverflow.com/questions/64089704/gitlab-runner-change-builds-dir

stages:
  - build

deploy-job:
  stage: build
  script:
    - npm run build
    - cp $ENV_FILE .env
    - chmod 600 .env
    - npm run deploy
  environment:
    name: production
  tags:
    - isbd-server
