variables:
  # GIT_CLONE_PATH: $CI_BUILDS_DIR/cloudflare-dns # https://stackoverflow.com/questions/64089704/gitlab-runner-change-builds-dir
  # GIT_CLEAN_FLAGS: none # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4154
  GIT_SUBMODULE_STRATEGY: recursive # https://docs.gitlab.com/ee/ci/git_submodules.html#use-git-submodules-in-cicd-jobs

stages:
  - build
  - deploy

build:
  image: docker:dind
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only: 
    - main
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - cp $ENV_FILE .env && chmod 600 .env
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker compose pull
    - docker-compose up -d
  only:
    - main
  environment: 
    name: production
  tags:
    - isbd-server
