variables:
  GIT_CLEAN_FLAGS: none # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4154

stages:
  - build
  - deploy

# TODO: Add test job
# TODO: Add on stop action for environment: https://docs.gitlab.com/ee/ci/environments/#stop-an-environment-through-the-ui

build-job:
  stage: build
  script:
    - npm run build
    - cp $ENV_FILE_PATH .env # copy environment file
    - chmod 600 .env
  environment:
    name: production

deploy-job:
  stage: deploy  
  script:
    - npm run start
  environment:
    name: production
    on_stop: stop-job

stop-job:
  script:
    - npm run stop
  environment:
    name: production
    action: stop
  when: manual