stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - npm run build
    - cp $ENV_FILE_PATH .env # copy environment file
    - chmod 600 .env
  environment:
    name: production

# TODO: Add test job

deploy-job:
  variables:
    GIT_CLEAN_FLAGS: none # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4154
  stage: deploy  
  script:
    - npm run start
  environment:
    name: production