stages:
  - deploy

# TODO: Add test job

deploy-job:
  stage: deploy  
  script:
    - npm run build
    - cp $ENV_FILE_PATH .env # copy environment file
    - npm run start
  environment:
    name: production