version: "3.8"

services:
  isbd-server:
    container_name: isbd-server
    build:
      context: ./
    entrypoint: [ "node", "build/index.js" ]
    volumes:
      - ${DATA_DIR?}:/app/data
      - .env:/app/.env
    ports:
      - ${MO_TCP_PORT?}:${MO_TCP_PORT}
    restart: always

# volumes:
#   data:
