version: "3"

services:
  isbd-server:
    container_name: isbd-server
    image: registry.glab.lromeraj.net/ucm/miot/tfm/isbd-server:latest
    volumes: 
      - data:/isbd-server/data
      - .env:/isbd-server/.env
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    ports:
      - ${MO_TCP_PORT}:${MO_TCP_PORT}
    restart: always

volumes:
  data:
